# Generated by Django 3.0.3 on 2020-02-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=40)),
                ('num', models.FloatField(default=0)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='polls.Title')),
            ],
        ),
    ]
