# Generated by Django 3.0.3 on 2020-02-24 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名')),
                ('img', models.ImageField(upload_to='', verbose_name='商品图片')),
                ('price', models.FloatField(verbose_name='价格')),
                ('size', models.CharField(max_length=30, verbose_name='尺寸')),
                ('matures', models.CharField(max_length=30, verbose_name='成熟期')),
                ('describe', models.CharField(max_length=100, verbose_name='描述')),
                ('explain', models.CharField(max_length=500, verbose_name='说明')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='评论人')),
                ('body', models.CharField(max_length=500, verbose_name='评论内容')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Goods', verbose_name='所属商品')),
            ],
        ),
    ]
