# Generated by Django 3.0.3 on 2020-02-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='img',
            field=models.ImageField(upload_to='ads', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='商品图片'),
        ),
    ]
