# Generated by Django 3.0.3 on 2020-02-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200225_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='tags',
            field=models.ManyToManyField(to='shop.Tag'),
        ),
    ]
