# Generated by Django 3.0.4 on 2020-03-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InCake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodimgs',
            name='img',
            field=models.ImageField(upload_to='goodimg', verbose_name='商品展示图'),
        ),
    ]
