# Generated by Django 3.0.4 on 2020-03-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InCake', '0002_auto_20200309_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='name_c',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='good',
            name='name_e',
        ),
    ]
